version: "3"

services:
  compiler:
    build:
      context: .
      dockerfile: clang.dockerfile
      # dockerfile: gcc.dockerfile
      args:
        WORKDIR: $WORKDIR
    image: cebnf-test
    volumes:
      - "./cebnf:/$WORKDIR/cebnf"
      - "./convert:/$WORKDIR/convert"
      - "./frijson:/$WORKDIR/frijson"
    tty: true
